### ISSUE TITLE
The key you are authenticating with has been marked as read only

### ISSUE THREAD

**Issue by bennyn** [greenkeeperio/greenkeeper-lockfile#103]
I want to run `greenkeeper-lockfile-upload` on CircleCI but I am getting the following error:
> #!/bin/bash -eo pipefail
greenkeeper-lockfile-upload
ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.
>
>Please make sure you have the correct access rights
and the repository exists.
child_process.js:611
    throw err;
    ^
>
> Error: Command failed: git push gk-origin HEAD:greenkeeper/binance-api-node-0.5.2
ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.
>
> Please make sure you have the correct access rights
and the repository exists.
>
>    at checkExecSyncError (child_process.js:568:13)
    at execSync (child_process.js:608:13)
    at Module.upload [as exports] (/usr/local/share/.config/yarn/global/node_modules/greenkeeper-lockfile/upload.js:53:3)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/greenkeeper-lockfile/upload.js:56:37)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
Exited with code 1

Do I need to add a GitHub SSH Key on CircleCI to solve this issue?

**Comment by Realtin** [comment]
Hey @bennyn 
yes you do. Create one here: https://github.com/settings/tokens and make it available as `GH_TOKEN ` to your CI.
The Token needs read/write rights for the repository, there are lots of boxes that can be ticked when creating one but you probably don't need to tick any (except maybe for a private repo).
