### ISSUE TITLE
Lockfile update fails due to missing git identity

### ISSUE THREAD

**Issue by psirenny** [greenkeeperio/greenkeeper-lockfile#206]
When running **greenkeeper-lockfile-update** on CircleCI I get the following error(s):

```
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <circleci@38918a12148b.(none)>) not allowed
Cannot save the current index state
child_process.js:640
    throw err;
    ^

Error: Command failed: git stash
```

**Comment by janl** [comment]
@psirenny ah this is interesting. You can use `GK_LOCK_COMMIT_NAME` and `GK_LOCK_COMMIT_EMAIL` see https://github.com/greenkeeperio/greenkeeper-lockfile#configuration-options for details.

**Comment by psirenny** [comment]
I did try manually setting those environment variables to no avail. However, shouldn't those variables automatically default to `greenkeeperio-bot` and `support@greenkeeper.io`?

**Comment by villelahdenvuo** [comment]
Also getting this problem all of a sudden. I haven't changed my configs or anything, perhaps it started after updating to version 2.

**Comment by Koslun** [comment]
@janl 
Also getting this error with version 2 of this library, 2.8.0 to be specific. Worked out after downgrading back to version 1.

Using Node version 8.13.0, yarn version 1.12.3 on Codeship. I also didn't change my config other than updating the version. While I did try to set `GK_LOCK_COMMIT_NAME` and `GK_LOCK_COMMIT_EMAIL` to specific values mentions above, that didn't fix anything.

I finally tried actually setting the git variables to the mentioned variables as well:
```
  git config --global user.email "support@greenkeeper.io"
  git config --global user.name "greenkeeperio-bot"
```

This got it through some errors only to produce errors complaining about missing lock or shrink wrap files in some dependencies.

Here is a snippet of our original error:
```
From https://github.com/<redacted github url>
* [new branch]      154647052-optimize-rendering -> gk-origin/154647052-optimize-rendering
* [new branch]      154985890-administrating-parent-organisations -> gk-origin/154985890-administrating-parent-organisations
* [new branch]      156007520-basic-json-schema-validation -> gk-origin/156007520-basic-json-schema-validation
* [new branch]      157388536-sign-in-reactive-forms-refactor -> gk-origin/157388536-sign-in-reactive-forms-refactor
* [new branch]      fix/report-list-not-refreshed -> gk-origin/fix/report-list-not-refreshed
* [new branch]      gh-pages               -> gk-origin/gh-pages
* [new branch]      greenkeeper/@angular-devkit/build-angular-0.10.7 -> gk-origin/greenkeeper/@angular-devkit/build-angular-0.10.7
* [new branch]      greenkeeper/@angular/cli-7.0.7 -> gk-origin/greenkeeper/@angular/cli-7.0.7
* [new branch]      greenkeeper/@ngxs/devtools-plugin-3.3.1 -> gk-origin/greenkeeper/@ngxs/devtools-plugin-3.3.1
* [new branch]      greenkeeper/@ngxs/logger-plugin-3.3.1 -> gk-origin/greenkeeper/@ngxs/logger-plugin-3.3.1
* [new branch]      greenkeeper/@ngxs/router-plugin-3.3.1 -> gk-origin/greenkeeper/@ngxs/router-plugin-3.3.1
* [new branch]      greenkeeper/@ngxs/storage-plugin-3.3.1 -> gk-origin/greenkeeper/@ngxs/storage-plugin-3.3.1
* [new branch]      greenkeeper/@ngxs/store-3.3.1 -> gk-origin/greenkeeper/@ngxs/store-3.3.1
* [new branch]      greenkeeper/papaparse-4.6.2 -> gk-origin/greenkeeper/papaparse-4.6.2
* [new branch]      greenkeeper/rxjs-tslint-rules-4.13.0 -> gk-origin/greenkeeper/rxjs-tslint-rules-4.13.0
* [new branch]      greenkeeper/sweetalert2-7.29.2 -> gk-origin/greenkeeper/sweetalert2-7.29.2
* [new branch]      master                 -> gk-origin/master
* [new branch]      message-empty-report-requests -> gk-origin/message-empty-report-requests
* [new branch]      new-toolbar            -> gk-origin/new-toolbar
* [new branch]      newLanguageKeys        -> gk-origin/newLanguageKeys
* [new branch]      newUploadTemplate      -> gk-origin/newUploadTemplate
* [new branch]      report-delete-disclosure-dynamic-form -> gk-origin/report-delete-disclosure-dynamic-form
* [new branch]      revert-113-feat/ng6    -> gk-origin/revert-113-feat/ng6
* [new branch]      revert-396-162015415-upgrade-angular-7 -> gk-origin/revert-396-162015415-upgrade-angular-7
* [new branch]      staging                -> gk-origin/staging
* [new branch]      transaction-product-fields-editable -> gk-origin/transaction-product-fields-editable
* [new branch]      transactions-filter-datasources-fetch-change -> gk-origin/transactions-filter-datasources-fetch-change
<<< REDACTED OTHER ≈100s of branches with similar-looking messages >>>

*** Please tell me who you are.

Run

git config --global user.email "you@example.com"
git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'rof@railsonfire_57063507-e4a8-4a2f-af17-95c18e90c7c6_27dd573d860c.(none)')
Cannot save the current index state
child_process.js:645
throw err;
^

Error: Command failed: git stash

*** Please tell me who you are.

Run

git config --global user.email "you@example.com"
git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'rof@railsonfire_57063507-e4a8-4a2f-af17-95c18e90c7c6_27dd573d860c.(none)')
Cannot save the current index state

at checkExecSyncError (child_process.js:602:13)
at execSync (child_process.js:642:13)
at hasLockfileCommit (/home/rof/.nvm/versions/node/v8.13.0/lib/node_modules/greenkeeper-lockfile/lib/git-helpers.js:57:5)
at Module.update [as exports] (/home/rof/.nvm/versions/node/v8.13.0/lib/node_modules/greenkeeper-lockfile/update.js:50:7)
at Object.<anonymous> (/home/rof/.nvm/versions/node/v8.13.0/lib/node_modules/greenkeeper-lockfile/update.js:116:37)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
```

And here is a snippet of the error after manually adding a git config:
```
From https://github.com/<<REDACTED PROJECT URL>>
* [new branch]      154647052-optimize-rendering -> gk-origin/154647052-optimize-rendering
* [new branch]      154985890-administrating-parent-organisations -> gk-origin/154985890-administrating-parent-organisations
* [new branch]      155061177-always-save-file-s3-bucket -> gk-origin/155061177-always-save-file-s3-bucket
* [new branch]      156007520-basic-json-schema-validation -> gk-origin/156007520-basic-json-schema-validation
* [new branch]      revert-113-feat/ng6    -> gk-origin/revert-113-feat/ng6
* [new branch]      revert-396-162015415-upgrade-angular-7 -> gk-origin/revert-396-162015415-upgrade-angular-7
* [new branch]      staging                -> gk-origin/staging
* [new branch]      transaction-product-fields-editable -> gk-origin/transaction-product-fields-editable
* [new branch]      transactions-filter-datasources-fetch-change -> gk-origin/transactions-filter-datasources-fetch-change
<<< REDACTED OTHER ≈100s of branches with similar-looking messages >>>
Previous HEAD position was b8f8f5b3 chore(package): update @angular/cli to version 7.1.0
Switched to a new branch 'develop'
Note: checking out 'b8f8f5b345c520b078609577899a7f68b0e3e3c5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

git checkout -b <new-branch-name>

HEAD is now at b8f8f5b3 chore(package): update @angular/cli to version 7.1.0
warning " > @auth0/angular-jwt@2.0.0" has incorrect peer dependency "@angular/common@^6.0.0".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-array@^1.2.1".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-brush@^1.0.4".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-color@^1.0.3".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-force@^1.1.0".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-format@^1.2.0".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-hierarchy@^1.1.5".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-interpolate@^1.1.5".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-scale@^1.0.6".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-selection@^1.1.0".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-shape@^1.2.0".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-time-format@^2.1.0".
warning " > @swimlane/ngx-datatable@12.0.0" has incorrect peer dependency "@angular/common@<=6.0.0".
warning " > @swimlane/ngx-datatable@12.0.0" has incorrect peer dependency "@angular/compiler@<=6.0.0".
warning " > @swimlane/ngx-datatable@12.0.0" has incorrect peer dependency "@angular/core@<=6.0.0".
warning " > @swimlane/ngx-datatable@12.0.0" has incorrect peer dependency "@angular/platform-browser@<=6.0.0".
warning " > @swimlane/ngx-datatable@12.0.0" has incorrect peer dependency "@angular/platform-browser-dynamic@<=6.0.0".
warning " > angular2-json-schema-form@0.7.0-alpha.1" has incorrect peer dependency "@angular/cdk@^6.0.0-rc.12".
warning " > angular2-json-schema-form@0.7.0-alpha.1" has incorrect peer dependency "@angular/common@^6.0.0-rc.0 || ^6.0.0".
warning " > angular2-json-schema-form@0.7.0-alpha.1" has incorrect peer dependency "@angular/core@^6.0.0-rc.0 || ^6.0.0".
warning " > angular2-json-schema-form@0.7.0-alpha.1" has incorrect peer dependency "@angular/flex-layout@^6.0.0-beta.15".
warning " > angular2-json-schema-form@0.7.0-alpha.1" has incorrect peer dependency "@angular/forms@^6.0.0-rc.5".
warning " > angular2-json-schema-form@0.7.0-alpha.1" has incorrect peer dependency "@angular/material@^6.0.0-rc.12".
warning " > angular2-json-schema-form@0.7.0-alpha.1" has unmet peer dependency "lodash@4.x".
node_modules/JSONStream/package.json: Without either an "npm-shrinkwrap.json", "package-lock.json" or "yarn.lock" file present there is no need to run this script
node_modules/abbrev/package.json: Without either an "npm-shrinkwrap.json", "package-lock.json" or "yarn.lock" file present there is no need to run this script
node_modules/accepts/package.json: Without either an "npm-shrinkwrap.json", "package-lock.json" or "yarn.lock" file present there is no need to run this script
node_modules/acorn/package.json: Without either an "npm-shrinkwrap.json", "package-lock.json" or "yarn.lock" file present there is no need to run this script
node_modules/acorn-dynamic-import/package.json: Without either an "npm-shrinkwrap.json", "package-lock.json" or "yarn.lock" file present there is no need to run this script
node_modules/adm-zip/package.json: Without either an "npm-shrinkwrap.json", "package-lock.json" or "yarn.lock" file present there is no need to run this script
node_modules/after/package.json: Without either an "npm-shrinkwrap.json", "package-lock.json" or "yarn.lock" file present there is no need to run this script
node_modules/@ngtools/webpack/node_modules/is-glob/package.json: Without either an "npm-shrinkwrap.json", "package-lock.json" or "yarn.lock" file present there is no need to run this script
node_modules/@ngtools/webpack/node_modules/json-schema-traverse/package.json: Without either an "npm-shrinkwrap.json", "package-lock.json" or "yarn.lock" file present there is no need to run this script
node_modules/@ngtools/webpack/node_modules/source-map/package.json: Without either an "npm-shrinkwrap.json", "package-lock.json" or "yarn.lock" file present there is no need to run this script
module.js:675
<<<< REDACTED 1000s similar looking lines for brevity>>>>
throw err;
^

SyntaxError: /home/rof/src/github.com/<<REDACTED PROJECT URL>>/node_modules/@schematics/angular/workspace/files/package.json: Unexpected token < in JSON at position 1121
at JSON.parse (<anonymous>)
at Object.Module._extensions..json (module.js:672:27)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Module.require (module.js:597:17)
at requireRelative (/home/rof/.nvm/versions/node/v8.13.0/lib/node_modules/greenkeeper-lockfile/node_modules/require-relative/index.js:25:15)
at allPackageFiles.reduce (/home/rof/.nvm/versions/node/v8.13.0/lib/node_modules/greenkeeper-lockfile/update.js:72:17)
at Array.reduce (<anonymous>)
at Module.update [as exports] (/home/rof/.nvm/versions/node/v8.13.0/lib/node_modules/greenkeeper-lockfile/update.js:61:36)
```
