### ISSUE TITLE
"error Missing list of packages to add to your project."

### ISSUE THREAD

**Issue by jbhannah** [greenkeeperio/greenkeeper-lockfile#28]
[With yarn on Travis CI](https://travis-ci.org/thetallgrassnet/pokesite/builds/239504543):

```
$ greenkeeper-lockfile-update
error Missing list of packages to add to your project.
child_process.js:518
    throw err;
    ^
Error: Command failed: yarn add -S  style-loader@0.18.2
error Missing list of packages to add to your project.
    at checkExecSyncError (child_process.js:475:13)
    at execSync (child_process.js:515:13)
    at updateLockfile (/home/travis/.config/yarn/global/node_modules/greenkeeper-lockfile/lib/update-lockfile.js:34:7)
    at Module.update [as exports] (/home/travis/.config/yarn/global/node_modules/greenkeeper-lockfile/update.js:49:3)
    at Object.<anonymous> (/home/travis/.config/yarn/global/node_modules/greenkeeper-lockfile/update.js:56:37)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

`-S` doesn't appear to be a valid option for `yarn add`.

**Comment by jbhannah** [comment]
[My Travis CI config](https://github.com/thetallgrassnet/pokesite/blob/27cde1f4d3951766ba96c37ecc9b49c28448aa54/.travis.yml) as of that build.

**Comment by janl** [comment]
Fixed in https://github.com/greenkeeperio/greenkeeper-lockfile/commit/d5c31298a114b68dec5410622b35749f3161427b
