### ISSUE TITLE
Strict mode error on Travis with Node.js 4 or 5

### ISSUE THREAD

**Issue by jogold** [greenkeeperio/greenkeeper-lockfile#37]
Hello,

When running `greenkeeper-lockfile-upload` on Travis with Node.js 4 or 5, I'm getting a strict mode error. Shouldn't `'use strict'` be added to `update.js` and `upload.js`?

```
/home/travis/.nvm/versions/node/v5.12.0/lib/node_modules/greenkeeper-lockfile/upload.js:36
  let remote = `git@github.com:${info.repoSlug}`
  ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

**Comment by jogold** [comment]
The error can been seen here also: https://travis-ci.org/greenkeeperio/greenkeeper-lockfile/jobs/242501059
