### ISSUE TITLE
Fails on Semaphore CI

### ISSUE THREAD

**Issue by HaoZeke** [greenkeeperio/greenkeeper-lockfile#96]
As per the settings,

I have 

```bash
yarn global add greenkeeper-lockfile@1
yarn
```

Then before my build, when I run 

```bash
greenkeeper-lockfile-update
```

I get:

```bash
/home/runner/.config/yarn/global/node_modules/greenkeeper-lockfile/ci-services/bitrise.js:8
  const repoUrlWithoutGitExtension = repoUrl.replace('.git', '')
                                             ^

TypeError: Cannot read property 'replace' of undefined
    at parseRepoSlug (/home/runner/.config/yarn/global/node_modules/greenkeeper-lockfile/ci-services/bitrise.js:8:46)
    at Object.<anonymous> (/home/runner/.config/yarn/global/node_modules/greenkeeper-lockfile/ci-services/bitrise.js:19:13)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at module.exports (/home/runner/.config/yarn/global/node_modules/greenkeeper-lockfile/ci-services/index.js:12:10)
```

Any suggestions?

**Comment by brunocascio** [comment]
Same here

**Comment by Realtin** [comment]
Hey, Semaphore CI has not yet been contributed. 
Supported CI Services so far: https://github.com/greenkeeperio/greenkeeper-lockfile#ci-services
